// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BookenatorController from "./bookenator_controller"
application.register("bookenator", BookenatorController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ReviewanatorController from "./reviewanator_controller"
application.register("reviewanator", ReviewanatorController)

import TabulatorController from "./tabulator_controller"
application.register("tabulator", TabulatorController)
